
services:
    api:
        image: ysof_api
        restart: unless-stopped
        depends_on:
            - mongodb
            - rabbit
        networks:
            - localnet
        volumes:
            - ./logs:/usr/src/app/logs
        cap_add:
            - SYS_ADMIN

    mongodb:
        image: mongo:7.0.2-jammy
        restart: always
        healthcheck:
            test: |
                mongosh --username ${MONGODB_USERNAME} --password ${MONGODB_PASSWORD} --eval "rs.initiate()"
            start_period: 0s
            interval: 10s
            timeout: 5s
            retries: 5
        command: >
            --bind_ip_all --replSet rs0 --keyFile /keyfile
        volumes:
            - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
            - mongodb_data:/data/db
            - ./keyfile:/keyfile
        networks:
            - localnet

    rabbit:
        image: rabbitmq:3-management
        container_name: base_rabbitmq
        volumes:
            - rabbit_data:/var/lib/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_DEFAULT_VHOST: /
        networks:
            - localnet

    celery:
        image: ysof_celery
        build:
            context: .
            dockerfile: celery.Dockerfile
        restart: on-failure
        volumes:
            - ./logs:/usr/src/app/logs
        environment:
            - C_FORCE_ROOT=true
        depends_on:
            - api
            - rabbit
            - mongodb
        networks:
            - localnet

networks:
    localnet:
        driver: bridge

volumes:
    mongodb_data:
        driver: local
    rabbit_data:
        driver: local
